name       : goldendict
version    : 1.5.0_rc2
release    : 9
source     :
    - https://github.com/goldendict/goldendict/archive/6d46fd15299657860ebaedf856494de0fdfdc756/goldendict-6d46fd15299657860ebaedf856494de0fdfdc756.tar.gz : 208167b48a01c05ddd0725d2f15b4860210e57677872c83b21388e4a4c11d40b
homepage   : http://goldendict.org/
license    : GPL-3.0-or-later
component  : office
summary    : Feature-rich dictionary lookup program, supporting multiple dictionary formats
description: |
    Feature-rich dictionary lookup program, supporting multiple dictionary formats (StarDict/Babylon/Lingvo/Dictd) and online dictionaries, featuring perfect article rendering with the complete markup, illustrations and other content retained and allowing you to type in words without any accents or correct case.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(ao)
    - pkgconfig(hunspell)
    - pkgconfig(libavutil)
    - pkgconfig(libtiff-4)
    - pkgconfig(liblzma)
    - pkgconfig(vorbisfile)
    - pkgconfig(xtst)
    - bzip2-devel
    - lzo-devel
setup      : |
    %qmake "CONFIG+=no_epwing_support zim_support" PREFIX="/usr"
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
